#!/bin/bash
if [ $USER != "openhab" ]; then
    sudo -s -u openhab
    echo "Changed user to " $USER
fi

cd /home/pi/gitrepos/mijnsensors/pilightMqttOsgi/src/main/resources

git pull
cp -a --update nl/vandenzen.iot/pilightmqttosgi-features.xml /usr/share/apache-karaf/deploy
# not needed: cp -a --update OSGI-INF/blueprint/blueprint.xml /usr/share/apache-karaf/deploy