pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'cd pilightMqttOsgi;mvn clean install'
            }
        }
        stage('Deploy') {
            environment {
                PI_RPI3_CREDS = credentials('pi_rpi3')
            }
            steps {
                sh 'cd pilightMqttOsgi;sshpass -p $PI_RPI3_CREDS_PSW rsync target/pilightMqttOsgi-1.0-SNAPSHOT.jar pi@rpi3:/usr/share/karaf/deploy'
            }
        }
    }
}

