pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'cd pilightMqttOsgi;mvn clean install'
            }
        }
        stage('Deploy') {
            environment {
                PI_RPI3_CREDS = credentials('pi_rpi3')
                PI_USER='pi'
                PI_HOST='rpi3.home'
            }
            steps {
                // remove old file
                sh 'sshpass -p $PI_RPI3_CREDS_PSW ssh $PI_USER@$PI_HOST \'rm --force /usr/share/karaf/deploy/pigpioj-java-*.jar\''
                sh 'cd pilightMqttOsgi;sshpass -p $PI_RPI3_CREDS_PSW rsync target/pilightMqttOsgi-1.0-SNAPSHOT.jar $PI_USER@$PI_HOST:/usr/share/karaf/deploy'
                // sh 'cd pilightMqttOsgi;sshpass -p $PI_RPI3_CREDS_PSW rsync target/classes/OSGI-INF/blueprint/blueprint.xml $PI_USER@$PI_HOST:/usr/share/karaf/deploy'
                sh 'cd pilightMqttOsgi;sshpass -p $PI_RPI3_CREDS_PSW rsync target/classes/nl/vandenzen/iot/pilightmqttosgi-features.xml $PI_USER@$PI_HOST:/usr/share/karaf/deploy'
                // wrapper Karaf werkt niet, foutmelding Bundle-ManifestVersion is niet 2
                //sh 'sshpass -p $PI_RPI3_CREDS_PSW rsync /home/carl/.m2/repository/uk/pigpioj/pigpioj-java/2.5.7/pigpioj-java-*.jar $PI_USER@$PI_HOST:/usr/share/karaf/deploy'
            }
        }
    }
}

